#ifndef DEF_CARC_CONTROLS
#define DEF_CARC_CONTROLS

#include <stdlib.h>
#include <stdio.h>

typedef enum {
    CCDETAILS_TURN_RIGHT, CCDETAILS_TURN_LEFT, CCDETAILS_TURN_180,
    CCDETAILS_CUR_TILE,
    CCDETAILS_PAWN_NORMAL,
    CCDETAILS_PAWN_DOUBLE,
    CCDETAILS_PAWN_ARCHITECT,
    CCDETAILS_PAWN_PIG
} Carc_Controls;
#define TOTAL_NR_CONTROLS 8

#endif // DEF_CARC_CONTROLS
